Basic setup  Rails 7  for modern Hotel application
DeVuDeveloper/hotel pull request #1
Opened 2023-07-21 13:03 UTC by DeVuDeveloper

1. **Models and Database**:
   - Created essential models for hotels and rooms to efficiently manage room data.
   - Set up associations between models, ensuring data integrity and smooth interactions.
   - Implemented validation rules for model attributes, ensuring data accuracy.

2. **User Authentication and Roles**:
   - Integrated Devise gem for user authentication and registration.
   - Implemented user roles (Super Admin, Manager, Admin, Guest, and User) for different levels of access and control.

3. **User Interface (UI)**:
   - Developed a basic UI for the application, ensuring an appealing and user-friendly design.
   - Styled the application using Tailwind CSS, providing a professional and polished appearance.

4. **Translations**:
   - Enabled translation support for the application, allowing users to switch between English and Serbian languages.

5. **Image Upload**:
   - Utilized Active Storage for local image uploading from a user's PC.
   - Implemented image attachments for hotels and rooms, enhancing the visual representation of the application.

6. **Routes and Controllers**:
   - Defined routes and controllers for users, hotels, rooms, and other models.
   - Set up routes for user registration and login, as well as hotel and room management.

7. **Contact Form**:
   - Created a contact form to enable users to get in touch with the hotel administration easily.

8. **Testing**:
   - Wrote test cases for models to ensure proper functionality and data validation.
   - Conducted thorough testing of user registration and session management using Devise.

The changes have been carefully reviewed, and the application has been thoroughly tested to ensure a seamless and reliable user experience.

Please review and merge the pull request at your convenience. Thank you for your time and consideration.

Best regards,
Dejan

2023-08-09 16:27 UTC, muhammad-ur-rehman requested changes

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/admin/dashboard/rooms_controller.rb
> +  end
this is repeating alot

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/admin/dashboard/users_controller.rb
> +    @users = User.where.not(role: User.roles[:super_admin])
why first? it will not change position in only 1 entity in the DB

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/admin/dashboard/users_controller.rb
> +        format.turbo_stream { flash.now[:notice] = "User was successfully created." }
i18n

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/admin/dashboard/users_controller.rb
> +        format.turbo_stream { flash.now[:notice] = "User was successfully updated." }
i18n

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/admin/dashboard/users_controller.rb
> +    @user.destroy
what if it is not destroyed

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/application_controller.rb
> +    I18n.locale = extract_locale || I18n.default_locale
when you are setting it why not using in the app

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/application_controller.rb
> +    end
i think now you should have an authenticator gem

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/home_controller.rb
> +    if @contact_form.save
if not>? in both cases it will render in 1 case with notification in other without notification i think there should be one in case failed

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/controllers/manager/dashboard_controller.rb
> +  before_action :authorize_manager!
repeating alot

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/helpers/reviews_helper.rb
> +module ReviewsHelper
you can remove these empty helpers in case they are not needed

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/javascript/gallery.js
> +
empty lines

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on app/views/admin/dashboard/rooms/index.html.erb
> +
in others as well

2023-08-09 16:27 UTC, muhammad-ur-rehman commented on db/migrate/20230720115830_create_rooms.rb
> +      t.text :description
in all migrations

2023-08-09 16:39 UTC, Nuri1977 approved these changes

2023-08-19 15:02 UTC, DeVuDeveloper commented on app/assets/config/manifest.js
> +
Thanks, done

2023-08-19 15:02 UTC, DeVuDeveloper commented on .github/workflows/linters.yml
> +        run: bin/bundle exec rspec spec
Done ,thank you!.

2023-08-19 15:22 UTC, DeVuDeveloper commented on app/controllers/admin/dashboard/hotels_controller.rb
> +    @hotels = Hotel.all
It is only one hotel.

2023-08-19 15:23 UTC, DeVuDeveloper commented on app/views/admin/dashboard/users/index.html.erb
> +
Done.

2023-08-19 15:37 UTC, DeVuDeveloper commented on db/migrate/20230720115830_create_rooms.rb
> +      t.text :description
thank you, changed :)

2023-08-23 05:48 UTC, muhammad-ur-rehman approved these changes

2023-08-23 14:41 UTC, merged